Repository spooooony/Spoony-Android, pull requests merged in 2025-04, with the labels that each got.

#219 [FIX/#218] 장소 상세 페이지 및 신고하기 페이지 유저 정보를 수정합니다.
  app/src/main/java/com/spoony/spoony/data/datasource/UserRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/UserService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/UserRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportState.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
Labels: FIX🔨, 🧡세홍🧡

#226 [FEAT/#225] Bottom Navibar UI 및 툴팁 arrow 위치 수정
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainTab.kt
  app/src/main/java/com/spoony/spoony/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/spoony/spoony/presentation/myPage/MyPageScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/myPage/navigation/MyPageNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/res/drawable/ic_mypage_gray400_24.xml
  app/src/main/res/drawable/ic_mypage_main400_24.xml
Labels: 💙민재💙, FEAT✨

#214 [FIX/#46] 탑앱바 컴포넌트 수정
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/CloseTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/SpoonyBasicTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TagTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TitleTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/component/MapSearchTopAppBar.kt
Labels: FIX🔨, ❤️효빈❤️

#232 [Feat/#231] Grapheme library를 적용했어요
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLargeTextField.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  gradle/libs.versions.toml
Labels: 💛동민💛, FEAT✨

#236 [FEAT/#222] 마이페이지 UI 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/LogoTag.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/bottomsheet/MapEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainTab.kt
  app/src/main/java/com/spoony/spoony/presentation/myPage/MyPageScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/myPage/navigation/MyPageNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/MyPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/component/MyPageTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/component/ProfileHeaderSection.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/component/ProfileIntroSection.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/component/ReviewCounter.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/navigation/MyPageNavigation.kt
  app/src/main/res/drawable/ic_checkbox_gray400.xml
  app/src/main/res/drawable/ic_checkbox_main400.xml
  app/src/main/res/drawable/ic_setting_24.xml
Labels: 💙민재💙, FEAT✨

#233 [FEAT/#230] 아이콘 드롭다운 공통 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dropdown/IconDropdown.kt
Labels: 🧡세홍🧡, FEAT✨

#240 [FEAT/#237] 팔로우 페이지 UI 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/BackAndMenuTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/FollowButton.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/FollowTabRow.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/FollowUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/PullToRefreshContainer.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/UserListScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/model/FollowType.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/model/UserItemUiState.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/navigation/FollowNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/MyPageRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/MyPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/mypage/navigation/MyPageNavigation.kt
  app/src/main/res/drawable/ic_kebabmenu_gray500_24.xml
Labels: 💙민재💙, FEAT✨

#238 [FEAT/#228] 스플래시, 로그인, 약관동의 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/core/designsystem/theme/Color.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/signin/SignInScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/signin/component/SocialLoginButton.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/signin/navigation/SignInNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/termsofservice/TermsOfServiceScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/termsofservice/component/AgreeAllButton.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/termsofservice/component/AgreeTermsButton.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/termsofservice/navigation/TermsOfServiceNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/splash/SplashActivity.kt
  app/src/main/java/com/spoony/spoony/presentation/splash/SplashScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/splash/navigation/SplashNavigation.kt
  app/src/main/res/drawable/ic_kakao_logo_18.xml
  app/src/main/res/drawable/ic_spoony_text_logo.xml
  app/src/main/res/drawable/img_login_background.png
  gradle/libs.versions.toml
Labels: ❤️효빈❤️, FEAT✨

#253 [FEAT/#246] 프로필 수정 바텀시트 만들기
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ImageHelperBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ImageHelperDragHandle.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ProfileImageCard.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/model/ProfileImageModel.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/navigation/ProfileEditNavgation.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageViewModel.kt
Labels: 💙민재💙, FEAT✨
