Repository spooooony/Spoony-Android, pull requests merged in 2025-06, with the labels that each got.

#328 [FEAT/#319] android 1st QA 반영
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
Labels: FIX🔨, 💛동민💛

#332 [FIX/#330] 안드 1차 qa 반영
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/UserListScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/UserScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/model/UserPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/OtherPageRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/navigation/OtherPageNavigation.kt
Labels: FIX🔨, 💙민재💙

#333 [FIX/#331] 안드 1차 QA 사항 반영
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TagTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchRecentItem.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchTopAppbar.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/DeleteReviewDialog.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/PlaceDetailBottomBar.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
Labels: FIX🔨, 🧡세홍🧡

#342 [FIX/#341] 기/디 1차 QA 반영
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyDatePickerBottomSheet.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/slider/SpoonySlider.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/data/datasource/TooltipPreferencesDataSource.kt
  app/src/main/java/com/spoony/spoony/data/di/TooltipPreferencesModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/FollowListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/FollowListMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/TooltipPreferencesRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/FollowListEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/TooltipPreferencesRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/FollowUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/UserListScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/model/UserItemUiState.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/navigation/FollowNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterEndScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/RegisterTooltip.kt
  app/src/main/java/com/spoony/spoony/presentation/register/model/RegisterState.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/model/BlockUserState.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/LocalReviewFilterCheckBox.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/UserScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/model/UserPageState.kt
  app/src/main/res/drawable/ic_checkbox_gray400.xml
  app/src/main/res/drawable/ic_slyder_thumb.xml
Labels: FIX🔨, 💙민재💙

#343 [FIX/#339] 온보딩, 스푼뽑기 QA 반영
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyNicknameTextField.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/SpoonDrawResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/SpoonDrawMapper.kt
  app/src/main/java/com/spoony/spoony/domain/entity/SpoonEntity.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapViewModel.kt
  app/src/main/res/drawable/ic_info_24.xml
  app/src/main/res/drawable/img_plastic_spoon.png
  app/src/main/res/drawable/img_wooden_spoon.png
  app/src/main/res/drawable/img_wooden_spoon_grey.png
  gradle/libs.versions.toml
Labels: FIX🔨, ❤️효빈❤️

#346 [FIX/#344] 지도 1차 QA
  app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/CloseTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapPlaceDetailCard.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/navigaion/MapNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/MapSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/navigation/MapSearchNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/component/MainBottomBar.kt
Labels: FIX🔨, ❤️효빈❤️

#348 [FEAT/#347] 설정의 사용자 차단 화면에서 pull to refresh 를 적용합니다.
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserViewModel.kt
Labels: 💛동민💛, FEAT✨

#350 [FIX/#349] 기디 1차 QA 추가 수정했습니다.
  app/src/main/java/com/spoony/spoony/data/dto/response/UserListSearchResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/UserInfoMapper.kt
  app/src/main/java/com/spoony/spoony/domain/entity/UserEntity.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/model/ExploreSearchUserModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/navigation/ExploreSearchNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
Labels: FIX🔨, 🧡세홍🧡

#357 [FIX/#356] 자기소개 아주 조금 수정
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/ProfileIntroSection.kt
Labels: FIX🔨, 💙민재💙

#359 [FEAT/#358] 2nd qa
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/main/SettingMainRoute.kt
Labels: 💛동민💛, FEAT✨

#361 [FEAT/#360] 유저 차단 화면에 empty뷰를 만들어요
  app/src/main/java/com/spoony/spoony/core/designsystem/component/screen/EmptyContent.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/UserScreen.kt
Labels: 💛동민💛, FEAT✨

#363 [FIX/#362] 탐색 뷰 서버통신 URL 변경
  app/src/main/java/com/spoony/spoony/data/datasource/ExploreRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/ExploreRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/ExplorePlaceReviewFilteredResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ExploreRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/ExploreService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/ExplorePlaceReviewResultEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/ExploreRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
Labels: FIX🔨, 🧡세홍🧡

#364 [FIX/#355] 지도 2차 QA
  app/proguard-rules.pro
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/TitleButtonDialog.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapCardPager.kt
Labels: FIX🔨, ❤️효빈❤️

#367 [FIX] 1차 실시간 QA 수정사항 수정
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/ScoopDialog.kt
Labels: FIX🔨, 🧡세홍🧡

#370 [FIX/#368] 등록 화면 로딩 추가 및 리컴포지션 최적화
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/component/PullToRefreshContainer.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
Labels: FIX🔨, 💙민재💙

#379 [Feat/#375] oss license 명시
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/presentation/setting/SettingRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/main/SettingMainRoute.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 💛동민💛, FEAT✨

#378 [FIX] 그림자 확장함수 수정
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/FilterChipRow.kt
Labels: FIX🔨, 💙민재💙, 🧡세홍🧡
