Repository spooooony/Spoony-Android, pull requests merged in 2025-01, with the labels that each got.

#7 [FEAT/#6] pr-checker 설정
  .github/CODEOWNERS
  .github/workflows/pr_checker.yml
  app/build.gradle.kts
Labels: ❤️효빈❤️, FEAT✨

#8 [Feat/#5] Design System Setting
  app/src/main/java/com/spoony/spoony/core/designsystem/theme/Color.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/theme/Theme.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/theme/Type.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: 🧡세홍🧡, FEAT✨

#19 [DOCS/#18] 리드미 수정
  README.md
Labels: ❤️효빈❤️, DOCS📜

#14 [ADD/#10] 아이콘 추가
  app/src/main/res/drawable/ic_add_map_gray400_24.xml
  app/src/main/res/drawable/ic_add_map_main400_24.xml
  app/src/main/res/drawable/ic_add_pin_main400_24.xml
  app/src/main/res/drawable/ic_american_24.xml
  app/src/main/res/drawable/ic_arrow_down_24.xml
  app/src/main/res/drawable/ic_arrow_left_24.xml
  app/src/main/res/drawable/ic_arrow_right_24.xml
  app/src/main/res/drawable/ic_arrow_up_24.xml
  app/src/main/res/drawable/ic_bar_24.xml
  app/src/main/res/drawable/ic_button_spoon_32.xml
  app/src/main/res/drawable/ic_cafe_24.xml
  app/src/main/res/drawable/ic_chinese_24.xml
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/drawable/ic_delete_filled_24.xml
  app/src/main/res/drawable/ic_delete_filled_gray100_24.xml
  app/src/main/res/drawable/ic_delete_outlined_24.xml
  app/src/main/res/drawable/ic_error_24.xml
  app/src/main/res/drawable/ic_explore_24.xml
  app/src/main/res/drawable/ic_filter_24.xml
  app/src/main/res/drawable/ic_japanese_24.xml
  app/src/main/res/drawable/ic_korean_24.xml
  app/src/main/res/drawable/ic_map_gray400_24.xml
  app/src/main/res/drawable/ic_map_main400_24.xml
  app/src/main/res/drawable/ic_pin_24.xml
  app/src/main/res/drawable/ic_plus_24.xml
  app/src/main/res/drawable/ic_radio_off_24.xml
  app/src/main/res/drawable/ic_radio_on_24.xml
  app/src/main/res/drawable/ic_register_24.xml
  app/src/main/res/drawable/ic_scooped_up_gray500_24.xml
  app/src/main/res/drawable/ic_search_24.xml
  app/src/main/res/drawable/ic_spoon_24.xml
  app/src/main/res/drawable/ic_spoon_cross_24.xml
  app/src/main/res/drawable/ic_views_grad_24.xml
  app/src/main/res/drawable/ic_world_24.xml
Labels: ❤️효빈❤️, ADD➕

#13 [Feat/#12] 공통 컴포넌트 button 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/button/SpoonyButton.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/type/ButtonStyles.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
Labels: 🧡세홍🧡, FEAT✨

#17 [Feat/#16] 공통 컴포넌트 Snackbar 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/snackbar/BasicSnackbar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/snackbar/TextSnackbar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/event/SnackbarTrigger.kt
Labels: 🧡세홍🧡, FEAT✨

#22 [Feat/#11] 공통 컴포넌트 Dialog 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SingleButtonDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SpoonyBasicDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/TwoButtonDialog.kt
Labels: 🧡세홍🧡, FEAT✨

#25 [Feat/#15] 공통 컴포넌트 TextField 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyBasicTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyIconButtonTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLargeTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLineTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonySearchTextField.kt
  app/src/main/res/drawable/ic_minus_gray400_24.xml
  app/src/main/res/values/strings.xml
Labels: 💙민재💙, FEAT✨

#28 [MOD/#27] IconChip, IconTag Icon 서버에서 이미지 URL 로 받도록 수정
  app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/IconTag.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/LogoTag.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/type/ChipColor.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/type/TagSize.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/ColorExt.kt
Labels: MOD✅, 🧡세홍🧡

#31 [FEAT/#23] TopAppBar 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/CloseTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/SpoonyBasicTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TagTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TitleTopAppBar.kt
Labels: ❤️효빈❤️, FEAT✨

#30 [Feat/#29] 장소 상세 페이지 Profile 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/UserProfileInfo.kt
Labels: 🧡세홍🧡, FEAT✨

#33 [Feat/#32] 장소 상세 페이지 IconDropdown 구현
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/IconDropdownMenu.kt
  app/src/main/res/drawable/ic_menu_24.xml
Labels: 🧡세홍🧡, FEAT✨

#37 [Feat/#36] PlaceDetailImageLazyRow UI 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/PlaceDetailImageLazyRow.kt
Labels: 🧡세홍🧡, FEAT✨

#41 [FEAT/#26] bottombar, 네비게이션 기본 세팅 구현
  app/src/main/java/com/spoony/spoony/core/navigation/MainTabRoute.kt
  app/src/main/java/com/spoony/spoony/core/navigation/Route.kt
  app/src/main/java/com/spoony/spoony/presentation/MainActivity.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainTab.kt
  app/src/main/java/com/spoony/spoony/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/navigaion/MapNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/navigation/RegisterNavigation.kt
  app/src/main/res/drawable/ic_explore_24.xml
  app/src/main/res/drawable/ic_explore_gray400_24.xml
  app/src/main/res/drawable/ic_explore_main400_24.xml
  app/src/main/res/drawable/ic_map_gray400_24.xml
  app/src/main/res/drawable/ic_map_main400_24.xml
  app/src/main/res/drawable/ic_register_24.xml
  app/src/main/res/drawable/ic_register_gray400_24.xml
  app/src/main/res/drawable/ic_register_main400_24.xml
  gradle/libs.versions.toml
Labels: 💙민재💙, FEAT✨

#42 [FEAT/#24] 바텀시트 컴포넌트 구현
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyAdvancedBottomSheet.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyBasicBottomSheet.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyBasicDragHandle.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/type/AdvancedSheetState.kt
  gradle/libs.versions.toml
Labels: ❤️효빈❤️, FEAT✨

#48 [Fix/#45] 버튼에 아이콘 넣게 되면 높이 달라지는 이슈 수정
  app/src/main/java/com/spoony/spoony/core/designsystem/component/button/SpoonyButton.kt
Labels: FIX🔨, 🧡세홍🧡

#50 [FIX/#49] 아이콘 사이즈 변경
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonySearchTextField.kt
Labels: FIX🔨, 💙민재💙

#47 [Feat/#44] top linear progress bar 구현
  app/src/main/java/com/spoony/spoony/presentation/register/componet/TopLinearProgressbar.kt
Labels: 💙민재💙, FEAT✨

#53 [FEAT/#52] SpoonyImage 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/image/SpoonyImage.kt
Labels: ❤️효빈❤️, FEAT✨

#61 [FEAT/#43] 메인 지도뷰 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyBasicDragHandle.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/MapPlaceDetailCard.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapBottomSheetDragHandle.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapListItem.kt
Labels: ❤️효빈❤️, FEAT✨

#64 [FEAT/#62] 지도 검색 뷰 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchEmptyResultScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchRecentEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchRecentItem.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchResultItem.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchTopAppBar.kt
Labels: ❤️효빈❤️, FEAT✨

#54 [FEAT/#51] 메뉴 추가 버튼 구현
  app/src/main/java/com/spoony/spoony/presentation/register/componet/AddMenuButtton.kt
Labels: 💙민재💙, FEAT✨

#57 [Feat/#55] NextButton 구현
  app/src/main/java/com/spoony/spoony/presentation/register/componet/NextButton.kt
Labels: 💙민재💙, FEAT✨

#68 [FEAT/#58] CustomDropDownMenu 구현
  app/src/main/java/com/spoony/spoony/presentation/register/componet/CustomDropDownMenu.kt
Labels: 💙민재💙, FEAT✨

#74 [FEAT/#73] SearchResultItem 구현
  app/src/main/java/com/spoony/spoony/presentation/register/componet/SearchResultItem.kt
Labels: 💙민재💙, FEAT✨

#76 [FEAT/#70] PhotoPicker 구현
  app/src/main/java/com/spoony/spoony/presentation/register/component/AddMenuButtton.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/CustomDropDownMenu.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/NextButton.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/PhotoPicker.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/SearchResultItem.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/TopLinearProgressBar.kt
Labels: 💙민재💙, FEAT✨

#63 [Feat/#60] 신고하기 페이지 Navigation 초기세팅 및 UI 구현
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportState.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/report/component/ReportRadioButton.kt
  app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/report/type/ReportOption.kt
Labels: 🧡세홍🧡, FEAT✨

#72 [FEAT/#65] 탐색뷰 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/SortingOption.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreItem.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreLocationBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreLocationDragHandle.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreSortingBottomSheet.kt
  app/src/main/res/raw/spoony_explore_empty.lottie
Labels: ❤️효빈❤️, FEAT✨

#85 [FIX/#84] IconTag 색상 값 String 에서 Color 값 넘기로도록 수정
  app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/IconTag.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreItem.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/MapPlaceDetailCard.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapListItem.kt
Labels: FIX🔨, 🧡세홍🧡

#83 [FEAT/#82] 탐색 뷰 UI 구현
  app/src/main/java/com/spoony/spoony/domain/entity/CategoryEntity.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreState.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreLocationBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreSortingBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/FeedModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/type/SortingOption.kt
Labels: ❤️효빈❤️, FEAT✨

#86 [FEAT/#81] place detail dialog 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/ScoopDialog.kt
  app/src/main/res/raw/spoony_detail_use.lottie
Labels: 🧡세홍🧡, FEAT✨

#88 [FIX/#87] IconChip 구조 변경
  app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
Labels: FIX🔨, 🧡세홍🧡

#91 [Feat/#90] spoonyGradient Modifier Extension을 구현합니다.
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
Labels: 💛동민💛, FEAT✨

#93 [MOD/#92] Button Primary 색 추가에 따른 수정
  app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SingleButtonDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/TwoButtonDialog.kt
Labels: MOD✅, 🧡세홍🧡

#56 [Feat/#9] 장소 상세 페이지 navigation 및 UI 구현
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PostEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/UserEntity.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/StoreInfo.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
  app/src/main/res/drawable/ic_add_map_gray400_24.xml
  app/src/main/res/drawable/ic_add_map_main400_24.xml
Labels: 🧡세홍🧡, FEAT✨

#94 [FEAT/#59] 네이버 길찾기 기능 및 함수 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
Labels: 🧡세홍🧡, FEAT✨

#98 [FEAT/#95] 장소 상세 다이얼로그 연결하기
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
Labels: 🧡세홍🧡, FEAT✨

#104 [FEAT/#97] 배경색 설정 및 가로모드 막기
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/core/designsystem/theme/Theme.kt
  app/src/main/java/com/spoony/spoony/presentation/MainActivity.kt
  gradle/libs.versions.toml
Labels: ❤️효빈❤️, FEAT✨

#100 [FEAT/#99] 장소 상세 페이지 더미 데이터 구현
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/UserEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/PostRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/type/DropdownOption.kt
Labels: 🧡세홍🧡, FEAT✨

#108 [Feat/#103] 신고하기 페이지 대략적인 UI 마무리
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportState.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/report/component/ReportCompleteDialog.kt
  app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
Labels: 🧡세홍🧡, FEAT✨

#106 [FEAT/#105] 탐색 뷰 더미데이터 연결
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ExploreRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/FeedEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/ExploreRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreState.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/FeedModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
Labels: ❤️효빈❤️, FEAT✨

#109 [FEAT/#107] 지도 검색 뷰 더미데이터
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/LocationEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/MapRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchState.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/model/LocationModel.kt
Labels: ❤️효빈❤️, FEAT✨

#110 [Feat/#80] 게시물 등록 UI, 네비게이션 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyBasicTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyIconButtonTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLargeTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLineTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonySearchTextField.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegisterRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/RegisterEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/RegisterRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterState.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepOneScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepTwoScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/AddMenuButtton.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/NextButton.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/PhotoPicker.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/SearchResultItem.kt
  app/src/main/java/com/spoony/spoony/presentation/register/model/Category.kt
  app/src/main/java/com/spoony/spoony/presentation/register/model/Place.kt
  app/src/main/java/com/spoony/spoony/presentation/register/navigation/RegisterNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/register/navigation/RegisterRoute.kt
Labels: 💙민재💙, FEAT✨

#113 [FEAT/#112] 게시물 등록 다이얼로그 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SpoonyBasicDialog.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepTwoScreen.kt
  app/src/main/res/raw/spoony_register_get.lottie
Labels: 💙민재💙, FEAT✨

#116 [FIX#115] unselected text color 수정
  app/src/main/java/com/spoony/spoony/presentation/main/component/MainBottomBar.kt
Labels: 💙민재💙, FEAT✨

#114 [Feat/#101] 장소 상세 페이지, 신고하기 QA 수정사항 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/PlaceDetailBottomBar.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/report/component/ReportRadioButton.kt
Labels: 🧡세홍🧡, FEAT✨

#118 [Feat/#111] 게시물 조회 API 연결
  app/src/main/java/com/spoony/spoony/data/datasource/PostRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PostRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/base/BaseResponse.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/GetPostResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/GetPostResponseMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/PostService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PostEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/PostRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
Labels: 🧡세홍🧡, FEAT✨

#131 [MOD/#127] pr-checker 수정
  .github/workflows/pr_checker.yml
Labels: FIX🔨, ❤️효빈❤️

#121 [FEAT/#117] 장소 검색 API 세팅
  app/src/main/java/com/spoony/spoony/data/datasource/PlaceDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PlaceDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/PlaceResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/PlaceMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegisterRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/PlaceService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PlaceEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/RegisterRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
Labels: 💙민재💙, FEAT✨

#124 [FEAT/#79] 지도 UI 구현 및 더미 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/LogoTag.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/AddedPlaceEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/MapRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapState.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/MapPlaceDetailCard.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapBottomSheetDragHandle.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapListItem.kt
  app/src/main/java/com/spoony/spoony/presentation/map/model/LocationModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/navigaion/MapNavigation.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ❤️효빈❤️, FEAT✨

#133 [Feat/#126] 카테고리 API (일반, 음식) 연결
  app/src/main/java/com/spoony/spoony/data/datasource/CategoryDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/CategoryDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/CategoryResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/CategoryMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/CategoryRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegisterRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/CategoryService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/CategoryRepository.kt
  app/src/main/java/com/spoony/spoony/domain/repository/RegisterRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
Labels: 💙민재💙, FEAT✨

#132 [FEAT/#128] 게시물 지도 리스트 추가 API 연결
  app/src/main/java/com/spoony/spoony/data/datasource/PostRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PostRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/request/AddMapRequestDto.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/PostService.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
Labels: 🧡세홍🧡, FEAT✨

#136 [FEAT/#130] 지도 리스트의 특정 리뷰 삭제 API 연결
  app/src/main/java/com/spoony/spoony/data/datasource/PostRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PostRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/PostService.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
Labels: 🧡세홍🧡, FEAT✨

#139 [FEAT/#137] 신고하기 페이지 신고하기 기능 및 API 구현
  app/src/main/java/com/spoony/spoony/data/datasource/ReportDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/ReportDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/request/ReportPostRequestDto.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ReportRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/ReportService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/ReportRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportState.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
Labels: 🧡세홍🧡, FEAT✨

#141 [FEAT/#125] 유저 정보 조회 API 연결
  app/src/main/java/com/spoony/spoony/core/util/UserId.kt
  app/src/main/java/com/spoony/spoony/data/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/UserInfoResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/UserInfoMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/AuthService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/AuthRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapState.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapViewModel.kt
Labels: ❤️효빈❤️, FEAT✨

#145 [FIX/#143] 장소 상세 페이지 날짜 년월일 포멧 함수 구현
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
Labels: 🧡세홍🧡, FEAT✨

#149 [MOD/#148] 게시물 조회 API DTO 수정
  app/src/main/java/com/spoony/spoony/data/dto/response/GetPostResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/GetPostResponseMapper.kt
Labels: MOD✅, 🧡세홍🧡

#150 [FEAT/#140] 사용자의 현재 스푼 개수 조회 API 구현
  app/src/main/java/com/spoony/spoony/data/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/UserSpoonCountResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/AuthService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/AuthRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
Labels: 🧡세홍🧡, FEAT✨

#151 [FEAT/#146] 장소 상세 페이지 사용자 정보 가져오기 API 붙이기
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
Labels: 🧡세홍🧡, FEAT✨

#154 [FEAT/#152] GetPostResponseDto isMine 추가 및 해당 게시글이 나의 글일 경우 분기 처리
  app/src/main/java/com/spoony/spoony/data/dto/response/GetPostResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/GetPostResponseMapper.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PostEntity.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/IconDropdownMenu.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/model/PostModel.kt
Labels: 🧡세홍🧡, FEAT✨

#160 [FEAT/#135] feat SplashActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/img_spoony_logo_86.xml
  app/src/main/res/values/themes.xml
Labels: 💛동민💛, FEAT✨

#156 [MOD/#155] 장소 상세 페이지 spoony_detail_use 변경
  app/src/main/res/raw/spoony_detail_use.lottie
Labels: MOD✅, 🧡세홍🧡

#158 [FIX/#157] user_id -> core 패키지 안 USER_ID 사용하도록 수정
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportState.kt
  app/src/main/java/com/spoony/spoony/presentation/report/ReportViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/report/navigation/ReportNavigation.kt
Labels: FIX🔨, 🧡세홍🧡

#161 [FIX/#159] topbar color 수정
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/CloseTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/SpoonyBasicTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TagTopAppBar.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/TitleTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
Labels: FIX🔨, 🧡세홍🧡

#147 [FEAT/#134] multipart 통신 구현
  app/src/main/java/com/spoony/spoony/data/datasource/PlaceDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PlaceDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/request/PlaceCheckRequestDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/request/RegisterPostRequestDto.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ContentUriRequestBody.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegisterRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/PostService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/RegisterRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepTwoScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/PhotoPicker.kt
Labels: 💙민재💙, FEAT✨

#168 [FEAT/#153] 지도 지역 검색 API 연결
  app/src/main/java/com/spoony/spoony/data/datasource/MapRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasource/PostRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/MapRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PostRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/LocationListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/ZzimLocationResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/LocationMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/ZzimLocaitonMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/MapService.kt
  app/src/main/java/com/spoony/spoony/data/service/PostService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/MapRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchEmptyResultScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchRecentEmptyScreen.kt
  app/src/main/res/drawable/img_map_search_location_empty.png
  app/src/main/res/drawable/img_map_search_recent_empty.png
Labels: ❤️효빈❤️, FEAT✨

#167 [FIX/#165] 장소 상세 페이지 프로필 info 위치 text 수정
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
Labels: FIX🔨, 🧡세홍🧡

#169 [FIX/#164] 신고하기 뷰에서 탐색 뷰 이동 시 nav 수정
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
Labels: FIX🔨, 🧡세홍🧡

#171 [FIX/#170] 스낵바 opacity 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/snackbar/BasicSnackbar.kt
Labels: FIX🔨, 🧡세홍🧡

#173 [FEAT/#166] 등록 툴팁 구현
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterState.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/RegisterTooltip.kt
  app/src/main/res/drawable/ic_register_tooltip_arrow.xml
  app/src/main/res/drawable/ic_tooltip_spoon_20.xml
Labels: 💙민재💙, FEAT✨

#172 [FEAT/#162] 지도 관련 API 구현
  app/src/main/java/com/spoony/spoony/data/datasource/PostRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PostRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/AddedMapListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/AddedMapPostListDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/GetPostResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/AddedMapMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/AddedMapPostMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/GetPostResponseMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/PostService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/AddedMapPostEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/AddedPlaceEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/MapRepository.kt
  app/src/main/java/com/spoony/spoony/domain/repository/PostRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapState.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/navigation/MapSearchNavigation.kt
  app/src/main/res/drawable/ic_selected_marker.xml
  app/src/main/res/drawable/ic_unselected_marker.xml
Labels: ❤️효빈❤️, FEAT✨

#175 [FIX/#174] 라지 텍스트 필드 오류 및 아이콘 텍스트 필드 QA반영
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyBasicTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyIconButtonTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLargeTextField.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepOneScreen.kt
Labels: 💙민재💙, FEAT✨

#180 [FEAT/#177] 탐색 뷰 사용자 스푼 개수 API 연결 및 장소 상세 떠먹었을 시 스푼 개수 업데이트
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
Labels: 🧡세홍🧡, FEAT✨

#181 [FIX/#163] imePadding 키보드 이슈 해결
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepOneScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/RegisterTooltip.kt
Labels: 💙민재💙, FEAT✨

#183 [FIX/#182] 툴팁 스테이트 오류 해결
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
Labels: FIX🔨, 💙민재💙
