Repository spooooony/Spoony-Android, pull requests merged in 2025-10, with the labels that each got.

#403 [FIX/#402] QA 반영했어요.
  app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterEndScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/model/RegisterState.kt
Labels: FIX🔨, 💙민재💙

#406 [ADD/#405] Firebase Crashlytics 설정 추가
  .github/workflows/pr_checker.yml
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 💙민재💙, ADD➕, FEAT✨

#394 [REFACTOR/#391] 탐색 뷰 리팩토링
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreState.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreFilterSection.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreHeaderSection.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreFilterBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/dialog/ReviewDeleteDialog.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/extension/ExploreFilterUtils.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/extension/MapExtensions.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/FilterOption.kt
Labels: REFACTOR🔃, 🧡세홍🧡

#399 [REF/#398] 탐색 검색 뷰 파라미터 줄이기 리펙토링
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchState.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/navigation/ExploreSearchNavigation.kt
Labels: REFACTOR🔃, 🧡세홍🧡
