Repository spooooony/Spoony-Android, pull requests merged in 2025-03, with the labels that each got.

#206 [MOD/#205] 등록화면 다음버튼 과 imePadding을 수정합니다.
  .github/CODEOWNERS
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepTwoScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/SearchResultItem.kt
Labels: MOD✅, 💙민재💙

#211 [FEAT/#197] 서버통신 로그 형식 수정
  app/src/main/java/com/spoony/spoony/core/network/JsonStringExt.kt
  app/src/main/java/com/spoony/spoony/core/network/RetrofitModule.kt
Labels: ❤️효빈❤️, FEAT✨

#210 [MOD/#207] 이미지 압축 로직을 다시한번 개선합니다 :(
  app/src/main/java/com/spoony/spoony/core/network/ContentUriRequestBody.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegisterRepositoryImpl.kt
Labels: MOD✅, 💙민재💙

#213 [REFACTOR/#202] 지도 뷰 리팩토링
  app/src/main/java/com/spoony/spoony/data/dto/response/AddedMapListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/AddedMapPostListDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/AddedMapMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/AddedMapPostMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/ZzimLocaitonMapper.kt
  app/src/main/java/com/spoony/spoony/domain/entity/AddedMapPostEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/AddedPlaceEntity.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapState.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapPlaceDetailCard.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/SpoonyMapMarker.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/bottomsheet/MapBottomSheetDragHandle.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/bottomsheet/MapEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/bottomsheet/MapListItem.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/model/LocationModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/navigaion/MapNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/MapSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/MapSearchState.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/MapSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/component/MapSearchEmptyResultScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/component/MapSearchRecentEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/component/MapSearchRecentItem.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/component/MapSearchResultItem.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/component/MapSearchTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/search/navigation/MapSearchNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainTab.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
  app/src/main/res/values/themes.xml
Labels: REFACTOR🔃, ❤️효빈❤️

#217 [REF/#212] 2차 스프린트 변경점 Register view에 반영합니다.
  app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SingleButtonDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SpoonyBasicDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/slider/SpoonySlider.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyBasicTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyIconButtonTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLargeTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLineTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonySearchTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyValidator.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterState.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepOneScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepTwoScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/RegisterTooltip.kt
  app/src/main/java/com/spoony/spoony/presentation/register/navigation/RegisterNavigation.kt
  app/src/main/res/drawable/ic_slyder_thumb.xml
Labels: REFACTOR🔃, 💙민재💙, FEAT✨
