Repository spooooony/Spoony-Android, pull requests merged in 2025-05, with the labels that each got.

#252 [Feat/#249] Blocking UI를 구현합니다.
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButton.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/model/BlockUserState.kt
Labels: 💛동민💛, FEAT✨

#256 [Feat/#250] 계정 관리 UI를 만들었서요
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
Labels: 💛동민💛, FEAT✨

#251 [Feat/#248] Setting UI를 구현합니다.
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/SettingRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButton.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/model/BlockUserState.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/navigation/SettingNavigation.kt
Labels: 💛동민💛, FEAT✨

#261 [FEAT/#243] 온보딩 컴포넌트 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/button/BirthSelectButton.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/button/RegionSelectButton.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyBasicTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyNicknameTextField.kt
  app/src/main/res/drawable/ic_check_16.xml
Labels: ❤️효빈❤️, FEAT✨

#257 [FEAT/#254] 리뷰 수정 UI만들었어요
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyIconButtonTextField.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainTab.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterEndScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStartScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/NextButton.kt
  app/src/main/java/com/spoony/spoony/presentation/register/component/SearchResultItem.kt
  app/src/main/java/com/spoony/spoony/presentation/register/model/RegisterType.kt
  app/src/main/java/com/spoony/spoony/presentation/register/navigation/RegisterNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/register/navigation/RegisterRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/UserScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/navigation/MyPageNavigation.kt
Labels: 💙민재💙, FEAT✨

#263 [FEAT/#239] 스플래시, 약관동의 내부 로직 구현
  app/src/main/java/com/spoony/spoony/data/datasource/local/TokenDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/local/TokenDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/TokenDataStoreModule.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/TokenRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/repository/TokenRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/termsofservice/TermsOfServiceScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/splash/SplashScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/splash/SplashViewModel.kt
Labels: ❤️효빈❤️, FEAT✨

#266 [Feat/#265] setting 내부 navigation을 구현합니다.
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/SettingRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButton.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/main/SettingMainRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/navigation/SettingNavigation.kt
Labels: 💛동민💛, FEAT✨

#272 [Feat/#247] settings UI 구현
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/SettingRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/BlockUserRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockButton.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/component/BlockUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/block/model/BlockUserState.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/main/SettingMainRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/navigation/SettingNavigation.kt
Labels: 💛동민💛, FEAT✨

#269 [FEAT/#260] 프로필 수정 UI 만듬
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyLocationBottomSheet.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/datepicker/SpoonyBasicPicker.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/BottomSheetProfileImageCard.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ImageHelperBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ProfileImageList.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/model/ProfileImageModel.kt
  app/src/main/res/drawable/ic_question_24.xml
Labels: 💙민재💙, FEAT✨

#255 [Feat/#224] 탐색 뷰 UI를 구현합니다.
  app/src/main/java/com/spoony/spoony/core/designsystem/component/card/ReviewCard.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ExploreRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/repository/ExploreRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreState.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreItem.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreTabRow.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/FilterChip.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/FilterChipRow.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreSortingBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/FilterOption.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/PlaceReviewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/res/drawable/ic_arrow_down_16.xml
  app/src/main/res/drawable/ic_filter_16.xml
  app/src/main/res/drawable/ic_search_20.xml
  app/src/main/res/drawable/ic_sort_filter_16.xml
Labels: 🧡세홍🧡, FEAT✨

#276 [REFACTOR/#274] 지역 선택 바텀시트 리팩토링
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyLocationBottomSheet.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyRegionBottomSheet.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/model/RegionModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditScreen.kt
Labels: REFACTOR🔃, ❤️효빈❤️

#258 [Feat/#229] 탐색 뷰 바텀시트 컴포넌트를 구현합니다.
  app/src/main/java/com/spoony/spoony/core/designsystem/component/chip/IconChip.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreFilterChip.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreFilterBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/ExploreFilter.kt
Labels: 🧡세홍🧡, FEAT✨

#277 [Feat/#271] 수정된 장소 상세 뷰를 구현합니다.
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/GetPostResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/GetPostResponseMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PlaceReviewEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PostEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/PostRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/DisappointItem.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/PlaceDetailBottomBar.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/PlaceDetailImageLazyRow.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/PlaceDetailSliderSection.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/StoreInfo.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/model/PlaceDetailModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/model/PostModel.kt
Labels: 🧡세홍🧡, FEAT✨

#273 [FEAT/#264] 스푼 뽑기 UI 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/LoadingDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SpoonDrawDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/TitleButtonDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/model/SpoonDrawModel.kt
  app/src/main/java/com/spoony/spoony/core/util/constants/StringConstants.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceState.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/component/SpoonInfoBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/navigation/AttendanceNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
  app/src/main/res/drawable/img_spoony.png
  app/src/main/res/drawable/img_wooden_spoon.png
  app/src/main/res/drawable/img_wooden_spoon_grey.png
Labels: ❤️효빈❤️, FEAT✨

#262 [Feat/#259] 탐색 검색 뷰를 구현합니다.
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchState.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchRecentEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchRecentItem.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchTopAppbar.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/navigation/ExploreSearchNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/type/SearchType.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
Labels: 🧡세홍🧡, FEAT✨

#279 [FEAT/#270] 유저페이지 미구현 부분 구현 완료!
  app/src/main/java/com/spoony/spoony/core/designsystem/component/button/FollowButton.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/slider/SpoonySlider.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/BackAndMenuTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/ProfileIntroSection.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/UserScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/model/UserPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/OtherPageRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/OtherPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/OtherPageViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/navigation/OtherPageNavigation.kt
Labels: 💙민재💙, FEAT✨

#281 [FEAT/#275] 온보딩 UI 구현
  app/src/main/java/com/spoony/spoony/core/designsystem/component/bottomsheet/SpoonyRegionBottomSheet.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyNicknameTextField.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/model/BirthDate.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingEndScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingState.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingStepOneScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingStepThreeScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingStepTwoScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/component/OnboardingButton.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/component/OnboardingContent.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/component/OnboardingTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/navigation/OnboardingRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/termsofservice/TermsOfServiceScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/termsofservice/navigation/TermsOfServiceNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
Labels: ❤️효빈❤️, FEAT✨

#282 [FEAT/#278] 지도 뷰 2스 수정사항 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/CloseTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapState.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/LocationPermissionDialog.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapTopAppBar.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/bottomsheet/MapEmptyScreen.kt
  app/src/main/res/drawable/ic_gps_24.xml
Labels: ❤️효빈❤️, FEAT✨

#286 [FEAT/#284] 탐색 UI 를 완성합니다.
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreState.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreTabRow.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/FilterChip.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/FilterChipRow.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/bottomsheet/ExploreFilterBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/ExploreFilter.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/FeedModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/FilterOption.kt
Labels: 🧡세홍🧡, FEAT✨

#290 [FEAT/#289] 스푼뽑기 API 연결
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SpoonDrawDialog.kt
  app/src/main/java/com/spoony/spoony/data/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasource/SpoonDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/SpoonDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/SpoonDrawListReponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/SpoonDrawResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/SpoonDrawListMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/SpoonDrawMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/SpoonRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/AuthService.kt
  app/src/main/java/com/spoony/spoony/data/service/SpoonService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/SpoonEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/AuthRepository.kt
  app/src/main/java/com/spoony/spoony/domain/repository/SpoonRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceState.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/OtherPageViewModel.kt
Labels: ❤️효빈❤️, FEAT✨

#288 [FEAT/#287] 탐색 검색 뷰 API 를 연결했습니다.
  app/src/main/java/com/spoony/spoony/core/util/extension/ColorExt.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/data/datasource/ExploreRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/ExploreRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/PlaceReviewListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/UserListSearchResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/PlaceReviewMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/UserInfoMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ExploreRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/ExploreService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/ExploreRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchState.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/model/ExploreSearchPlaceReviewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/model/ExploreSearchUserModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/navigation/ExploreSearchNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/type/ExploreDropdownOption.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
Labels: 🧡세홍🧡, FEAT✨

#294 [FEAT/#292] 장소 상세 페이지 API 연결하기 및 미구현 작업들 완료하기
  app/src/main/java/com/spoony/spoony/core/designsystem/component/slider/SpoonySlider.kt
  app/src/main/java/com/spoony/spoony/data/datasource/UserRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/request/FollowRequestDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/UserInfoResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/UserInfoMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/UserService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/UserEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/UserRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/component/DeleteReviewDialog.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/model/UserInfoModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/navigation/PlaceDetailNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/type/DropdownOption.kt
Labels: 🧡세홍🧡, FEAT✨

#301 [FEAT#300] 팔로우/팔로잉 페이지 API붙이기
  app/src/main/java/com/spoony/spoony/core/state/ErrorType.kt
  app/src/main/java/com/spoony/spoony/data/datasource/UserRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/BasicUserInfoResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/FollowListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/FollowListMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/UserService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/BasicUserInfoEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/FollowListEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/UserRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowManager.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/model/UserItemUiState.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/model/UserInfoModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/model/UserPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/mypage/MyPageViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/OtherPageViewModel.kt
Labels: 💙민재💙, FEAT✨

#305 [FEAT/#302] 유저 차단 API
  app/src/main/java/com/spoony/spoony/core/designsystem/component/button/FollowButton.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/topappbar/BackAndMenuTopAppBar.kt
  app/src/main/java/com/spoony/spoony/data/datasource/UserRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/request/TargetUserRequestDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/BasicUserInfoMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/UserService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/UserRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/follow/FollowRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/LocalReviewFilterCheckBox.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/component/UserScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/model/UserPageState.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/otherpage/OtherPageViewModel.kt
Labels: 💙민재💙, FEAT✨

#306 [FEAT/#304] 최근 유저 및 게시물 검색어 RoomDB로 저장
  app/src/main/java/com/spoony/spoony/core/database/ExploreRecentSearchDao.kt
  app/src/main/java/com/spoony/spoony/core/database/ExploreRecentSearchDatabase.kt
  app/src/main/java/com/spoony/spoony/core/database/di/LocalDatabaseModule.kt
  app/src/main/java/com/spoony/spoony/core/database/entity/ExploreRecentSearchEntity.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/UserListSearchResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ExploreRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/entity/UserEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/ExploreRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/ExploreSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/component/ExploreSearchUserItem.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/model/ExploreSearchUserModel.kt
Labels: 🧡세홍🧡, FEAT✨

#303 [FEAT/#295] 탐색 API 연결 및 탐색 뷰 관련 미구현 작업들을 완료합니다.
  app/src/main/java/com/spoony/spoony/core/designsystem/component/card/ReviewCard.kt
  app/src/main/java/com/spoony/spoony/data/datasource/ExploreRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasource/RegionRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/ExploreRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/RegionRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/DataSourceModule.kt
  app/src/main/java/com/spoony/spoony/data/di/RepositoryModule.kt
  app/src/main/java/com/spoony/spoony/data/di/ServiceModule.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/ExplorePlaceReviewFilteredResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/ExplorePlaceReviewFollowingResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/PlaceReviewListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/RegionListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ExploreRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegionRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/ExploreService.kt
  app/src/main/java/com/spoony/spoony/data/service/RegionService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/ExplorePlaceReviewResultEntity.kt
  app/src/main/java/com/spoony/spoony/domain/repository/ExploreRepository.kt
  app/src/main/java/com/spoony/spoony/domain/repository/RegionRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreState.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreEmptyScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/component/ExploreTabRow.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/ExploreFilter.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/PlaceReviewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/type/ExploreDropdownOption.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/type/SortingOption.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
Labels: 🧡세홍🧡, FEAT✨

#318 [MOD/#316] 프로필 수정 유즈케이스로 분리함
  app/src/main/java/com/spoony/spoony/core/util/extension/StringExt.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/ProfileImageResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/ProfileImageMapper.kt
  app/src/main/java/com/spoony/spoony/domain/entity/ProfileImageEntity.kt
  app/src/main/java/com/spoony/spoony/domain/usecase/CheckNicknameDuplicationUseCase.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditState.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/ProfileEditViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ImageHelperBottomSheet.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/component/ProfileImageList.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/model/ProfileEditModel.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/model/ProfileImageModel.kt
  app/src/main/java/com/spoony/spoony/presentation/profileedit/navigation/ProfileEditNavgation.kt
Labels: MOD✅, 💙민재💙

#317 [Feat/#315] 로그아웃/회원탈퇴 구현
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/data/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/AuthService.kt
  app/src/main/java/com/spoony/spoony/domain/repository/AuthRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountDeleteScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountManagementScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/setting/account/AccountViewModel.kt
  gradle/libs.versions.toml
Labels: 💛동민💛, FEAT✨

#320 [FEAT/#291] 스푼뽑기 dataStore 연결
  app/src/main/java/com/spoony/spoony/core/designsystem/component/dialog/SpoonDrawDialog.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/model/SpoonDrawModel.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/LocalDateExt.kt
  app/src/main/java/com/spoony/spoony/data/datasource/local/SpoonLocalDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/local/SpoonLocalDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/di/SpoonDataStoreModule.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/SpoonRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/domain/repository/SpoonRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceState.kt
  app/src/main/java/com/spoony/spoony/presentation/attendance/AttendanceViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/auth/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapSideEffect.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/navigaion/MapNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/res/drawable/img_spoon_draw_pick.png
  app/src/main/res/raw/spoony_spoon_draw_shake.lottie
Labels: ❤️효빈❤️, FEAT✨

#324 [FEAT/#312] 지도 API 적용
  app/src/main/java/com/spoony/spoony/data/datasource/PostRemoteDataSource.kt
  app/src/main/java/com/spoony/spoony/data/datasourceimpl/PostRemoteDataSourceImpl.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/AddedMapListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/AddedMapPostListDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/CategoryResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/PlaceReviewListResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/dto/response/ZzimLocationResponseDto.kt
  app/src/main/java/com/spoony/spoony/data/mapper/AddedMapMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/AddedMapPostMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/PlaceReviewMapper.kt
  app/src/main/java/com/spoony/spoony/data/mapper/ZzimLocaitonMapper.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/PostRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/data/service/PostService.kt
  app/src/main/java/com/spoony/spoony/domain/entity/AddedMapPostEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/AddedPlaceEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PlaceReviewEntity.kt
  app/src/main/java/com/spoony/spoony/domain/entity/PlaceReviewList.kt
  app/src/main/java/com/spoony/spoony/domain/repository/MapRepository.kt
  app/src/main/java/com/spoony/spoony/domain/repository/PostRepository.kt
  app/src/main/java/com/spoony/spoony/presentation/explore/model/PlaceReviewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/exploreSearch/model/ExploreSearchPlaceReviewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapState.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/MapPlaceDetailCard.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/component/SpoonyMapMarker.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/model/CategoryModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/model/PlaceReviewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/gourmet/map/model/ReviewCardModel.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/model/PlaceReviewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/userpage/model/UserPageState.kt
Labels: ❤️효빈❤️, FEAT✨
