Repository spooooony/Spoony-Android, pull requests merged in 2025-02, with the labels that each got.

#194 [HOTFIX/#193] 네비게이션 스택 수정 및 자잘한 디테일을 수정했습니다.
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/core/database/SearchDao.kt
  app/src/main/java/com/spoony/spoony/core/database/di/LocalDatabaseModule.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/tag/LogoTag.kt
  app/src/main/java/com/spoony/spoony/core/designsystem/component/textfield/SpoonyLargeTextField.kt
  app/src/main/java/com/spoony/spoony/core/util/extension/ModifierExt.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainNavigator.kt
  app/src/main/java/com/spoony/spoony/presentation/main/MainScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/MapViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/component/bottomsheet/MapListItem.kt
  app/src/main/java/com/spoony/spoony/presentation/map/navigaion/MapNavigation.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/MapSearchViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/map/search/component/MapSearchRecentItem.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailRoute.kt
  app/src/main/java/com/spoony/spoony/presentation/placeDetail/PlaceDetailViewModel.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepTwoScreen.kt
Labels: HOTFIX🚨, 💙민재💙

#200 [REF/#198] ContentUriRequest Class의 이미지 압축 방식을 개선합니다.
  app/build.gradle.kts
  app/src/main/java/com/spoony/spoony/core/network/ContentUriRequestBody.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/ContentUriRequestBody.kt
  app/src/main/java/com/spoony/spoony/data/repositoryimpl/RegisterRepositoryImpl.kt
Labels: REFACTOR🔃, 💙민재💙

#196 [CHORE/#195] 하드코딩 -> USER_ID 수정
  app/src/main/java/com/spoony/spoony/presentation/explore/ExploreViewModel.kt
Labels: ❤️효빈❤️, CHORE🎀

#201 [FEAT/#199] Register Screen step이동시 애니메이션을 추가합니다.
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepOneScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/RegisterStepTwoScreen.kt
  app/src/main/java/com/spoony/spoony/presentation/register/navigation/RegisterNavigation.kt
Labels: 💙민재💙, FEAT✨

#204 [MOD/#203] 최근 검색어 중복을 제거 하도록 수정합니다
  app/src/main/java/com/spoony/spoony/core/database/SearchDao.kt
Labels: MOD✅, 💙민재💙
